/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    branding: Branding;
    merchandise: Merchandise;
    advertising: Advertising;
    websites: Website;
    moodboard: Moodboard;
    snippets: Snippet;
    posts: Post;
    testimonials: Testimonial;
    services: Service;
    clients: Client;
    media: Media;
    subscribers: Subscriber;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    branding: BrandingSelect<false> | BrandingSelect<true>;
    merchandise: MerchandiseSelect<false> | MerchandiseSelect<true>;
    advertising: AdvertisingSelect<false> | AdvertisingSelect<true>;
    websites: WebsitesSelect<false> | WebsitesSelect<true>;
    moodboard: MoodboardSelect<false> | MoodboardSelect<true>;
    snippets: SnippetsSelect<false> | SnippetsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    contact: Contact;
    theme: Theme;
    identity: Identity;
    'loading-screen': LoadingScreen;
    legal: Legal;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    identity: IdentitySelect<false> | IdentitySelect<true>;
    'loading-screen': LoadingScreenSelect<false> | LoadingScreenSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Each project is one row on the Recent Work page (/work). Drag to reorder — the order here is the order visitors see. Use “Add to portfolio” on a project to also show it in a portfolio category.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Auto-filled from the title if left blank.
   */
  slug?: string | null;
  /**
   * Who it was for.
   */
  client?: string | null;
  year?: number | null;
  /**
   * Short tags — e.g. Identity, Web Design, Art Direction. Two or three is plenty.
   */
  disciplines?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One sentence on what this project was. Shown on its Recent Work row — keep it short; the image does the talking.
   */
  summary: string;
  /**
   * The single decisive image for this project. Landscape works best.
   */
  cover: number | Media;
  /**
   * Optional longer case study, shown on the project page.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The gap between the images below, in pixels. Set it to 0 when one artwork has been split across several files — the pieces then butt together with no seam.
   */
  galleryGap?: number | null;
  /**
   * More images from the project, stacked below the write-up. Leave empty to show just the cover. Two half-width images in a row sit side by side.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Optional. A short line under the image.
         */
        caption?: string | null;
        /**
         * Full images stand alone; two halves in a row share the width.
         */
        size?: ('full' | 'half') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show this project on the Recent Work page.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image the way you would to someone who cannot see it. This is read aloud by screen readers and shown if the image fails to load.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Branding pieces, shown as wide stacked thumbnails on the portfolio page. Link one to a Recent Work project and its thumbnail becomes clickable, opening that project’s full case study.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  title: string;
  /**
   * The piece itself — wide/landscape framing reads best here.
   */
  image: number | Media;
  /**
   * Optional. The Recent Work project this piece belongs to. When set, clicking the thumbnail opens that project’s full case study. (Copying a project in from Recent Work sets this automatically.)
   */
  project?: (number | null) | Project;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Merchandise shots, shown as an auto-scrolling carousel on the portfolio page. Square or product-on-plain-background images read best.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchandise".
 */
export interface Merchandise {
  id: number;
  title: string;
  /**
   * The product shot. It scrolls past in the carousel — consistent framing across items looks best.
   */
  image: number | Media;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Advertising design, shown as a gallery grid on the portfolio page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advertising".
 */
export interface Advertising {
  id: number;
  title: string;
  /**
   * The ad or campaign image.
   */
  image: number | Media;
  /**
   * Optional. A short line shown under the image.
   */
  caption?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Website design, shown inside a browser frame on the portfolio page. Upload a tall full-page screenshot — it scrolls inside the frame on hover.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "websites".
 */
export interface Website {
  id: number;
  /**
   * The project or client name.
   */
  title: string;
  /**
   * A tall, full-page screenshot of the site (capture the whole page, not just the top). It sits inside the browser frame and scrolls on hover.
   */
  screenshot: number | Media;
  /**
   * Optional. The real site address, e.g. https://example.com — shown in the frame’s address bar and makes the frame a link that opens the live site.
   */
  liveUrl?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images on the moodboard page, where visitors can pick up and move the blocks around. Mix the block sizes for a livelier wall.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moodboard".
 */
export interface Moodboard {
  id: number;
  title: string;
  /**
   * Any orientation — it fills its block.
   */
  image: number | Media;
  /**
   * How large this block sits on the board.
   */
  blockSize?: ('small' | 'medium' | 'large') | null;
  /**
   * Lower numbers appear first (before anyone moves things).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Screengrabs of work in progress, shown on the Snippets page. Each one is a 16:9 thumbnail visitors can click to enlarge, with a short note underneath.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "snippets".
 */
export interface Snippet {
  id: number;
  /**
   * For your own reference, and read aloud by screen readers.
   */
  title: string;
  /**
   * The screengrab. Thumbnails are 16:9, so a widescreen crop fills the frame — anything else is centred and cropped to fit. The full image is what opens when it’s clicked.
   */
  image: number | Media;
  /**
   * A sentence or two shown in the bubble under the image. Leave blank for none.
   */
  note?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Posts on the blog page. The Blog link only appears in the site header once at least one post is published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-filled from the title if left blank.
   */
  slug?: string | null;
  /**
   * Posts are ordered newest first by this date.
   */
  publishedAt: string;
  /**
   * Untick to keep a draft hidden from the site.
   */
  published?: boolean | null;
  /**
   * One or two sentences shown on the blog page under the title.
   */
  excerpt: string;
  /**
   * Optional. Shown on the blog page and at the top of the post.
   */
  cover?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Real words from real clients. If none are published, the homepage simply omits this section — it never shows an empty shell.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Keep it to what they actually said. Shorter quotes land harder.
   */
  quote: string;
  name: string;
  /**
   * e.g. Founder
   */
  role?: string | null;
  company?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Uncheck to hide without deleting.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The cards in the homepage Services section. Untick “Show on the site” to work on one without it appearing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * On by default. Untick to keep a service out of the Services section and the footer.
   */
  published?: boolean | null;
  /**
   * An image or GIF for the top of the card. Any shape works — it’s scaled to sit whole inside the card’s dotted area, never cropped, with the dots showing around it. GIFs keep their animation, and a PNG keeps its transparency.
   */
  image?: (number | null) | Media;
  /**
   * Two or three sentences on what the client gets. Optional — a card without one shows its title and price.
   */
  description?: string | null;
  /**
   * Written exactly as it should read — e.g. “$1,500 – $4,000”, “From $800”, or “Custom quote”. Leave blank to hide.
   */
  price?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The logos in the “Trusted by” strip under the homepage hero. They sit faded until hovered, so single-colour logos on a transparent background look most consistent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * The business’s name. Read aloud by screen readers in place of the logo.
   */
  name: string;
  /**
   * SVG or a transparent PNG, cropped close to the artwork — any empty margin around the logo makes it render smaller than its neighbours.
   */
  logo: number | Media;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who asked to hear about new work. Export or delete any time.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'branding';
        value: number | Branding;
      } | null)
    | ({
        relationTo: 'merchandise';
        value: number | Merchandise;
      } | null)
    | ({
        relationTo: 'advertising';
        value: number | Advertising;
      } | null)
    | ({
        relationTo: 'websites';
        value: number | Website;
      } | null)
    | ({
        relationTo: 'moodboard';
        value: number | Moodboard;
      } | null)
    | ({
        relationTo: 'snippets';
        value: number | Snippet;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  year?: T;
  disciplines?:
    | T
    | {
        label?: T;
        id?: T;
      };
  summary?: T;
  cover?: T;
  body?: T;
  galleryGap?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        size?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  project?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchandise_select".
 */
export interface MerchandiseSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advertising_select".
 */
export interface AdvertisingSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  caption?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "websites_select".
 */
export interface WebsitesSelect<T extends boolean = true> {
  title?: T;
  screenshot?: T;
  liveUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moodboard_select".
 */
export interface MoodboardSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  blockSize?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "snippets_select".
 */
export interface SnippetsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  note?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  published?: T;
  excerpt?: T;
  cover?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  company?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  published?: T;
  image?: T;
  description?: T;
  price?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every word on the homepage lives here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * The first thing anyone reads. Short — it is set very large, and long copy will not sit well.
   */
  heroLine: string;
  /**
   * One or two sentences under the headline.
   */
  heroIntro: string;
  /**
   * Shows a small live dot and the label below.
   */
  available?: boolean | null;
  availabilityLabel?: string | null;
  /**
   * Optional. Sits centred below the buttons.
   */
  heroImage?: (number | null) | Media;
  /**
   * How much of the hero’s width the photo takes up, on wide screens.
   */
  heroImageSize?: number | null;
  trustedHeading?: string | null;
  /**
   * The pill under the logos — e.g. “50+ More”. Leave blank to hide it.
   */
  trustedMoreLabel?: string | null;
  workHeading: string;
  /**
   * Optional. Leave blank to let the work start immediately.
   */
  workIntro?: string | null;
  servicesHeading?: string | null;
  /**
   * Optional. One line under the heading.
   */
  servicesIntro?: string | null;
  blogHeading: string;
  /**
   * Optional. A line under the heading on the blog page.
   */
  blogIntro?: string | null;
  metaDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The one obvious next step, and the softer fallback for people not ready yet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  heading: string;
  blurb?: string | null;
  /**
   * The primary call to action.
   */
  email: string;
  /**
   * Optional scheduling link (Cal.com, Calendly). Shown next to the email.
   */
  bookingUrl?: string | null;
  /**
   * The line under your name in the footer, on every page.
   */
  footerTagline?: string | null;
  newsletter?: {
    enabled?: boolean | null;
    blurb?: string | null;
  };
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Every colour on the site. Use each swatch to open a colour wheel, or type a hex code. The contrast panel below the neutrals updates live so you can see whether text stays readable. Toggle Live Preview (top right) to watch the homepage recolour as you edit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * The page background.
   */
  background: string;
  /**
   * Headings and body copy. Must read clearly on the background.
   */
  text: string;
  /**
   * Secondary text — captions, metadata, supporting lines.
   */
  mutedText: string;
  /**
   * Tinted panels, such as image frames. Usually a hair off the background.
   */
  surface: string;
  /**
   * Hairlines and dividers.
   */
  border: string;
  /**
   * Buttons, links, emphasis, and the whole contact section. Text on it stays readable automatically — pick any colour.
   */
  brandColor: string;
  /**
   * The single bright note — the “available for work” dot. Used only as a small mark, so it can be as vivid as you like.
   */
  signalColor: string;
  /**
   * Applies to buttons, inputs and image corners.
   */
  radius: 'sharp' | 'soft' | 'round';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The site’s name and logo, the browser tab’s icon and title, and how each is used.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity".
 */
export interface Identity {
  id: number;
  /**
   * Shown in the header when no logo is uploaded (or it’s turned off below), and in the footer.
   */
  siteName: string;
  /**
   * Optional. A wide logo with a transparent background works best — SVG or PNG.
   */
  logo?: (number | null) | Media;
  /**
   * Show the logo in the header instead of the site name.
   */
  showLogo?: boolean | null;
  /**
   * How tall the logo renders in the header, in pixels.
   */
  logoHeight?: number | null;
  /**
   * Shown in the browser tab and bookmarks. Square and simple reads best — most browsers render it very small.
   */
  favicon?: (number | null) | Media;
  /**
   * The browser tab’s title, and the page title search engines see. Short reads best — under ~60 characters.
   */
  browserTitle: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The intro that plays over the first page someone opens in a visit: your images flash by under a dark layer while your logo grows, then it fades to the site. It plays once per visit, never for people who have reduced motion turned on, and it hides itself until at least one image is added.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loading-screen".
 */
export interface LoadingScreen {
  id: number;
  enabled?: boolean | null;
  /**
   * How long each image stays on screen, in milliseconds (1000 = one second). Lower is faster. The logo grows across the whole run, so it slows or speeds up to match.
   */
  frameDuration?: number | null;
  /**
   * The tint laid over the images, under the logo.
   */
  overlayColor?: string | null;
  /**
   * How strongly the tint covers the images. 0 shows them untouched.
   */
  overlayOpacity?: number | null;
  /**
   * Up to 10, each on screen for half a second in this order — drag to reorder. Landscape photos at least 2000px wide look sharpest; they are shown filling the screen and cropped to fit.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Your Terms of Service and Privacy Policy. Each page, and its link in the footer, appears once it has text — leave one empty and it stays hidden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  /**
   * Shown at /terms.
   */
  terms?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown at /privacy.
   */
  privacy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroLine?: T;
  heroIntro?: T;
  available?: T;
  availabilityLabel?: T;
  heroImage?: T;
  heroImageSize?: T;
  trustedHeading?: T;
  trustedMoreLabel?: T;
  workHeading?: T;
  workIntro?: T;
  servicesHeading?: T;
  servicesIntro?: T;
  blogHeading?: T;
  blogIntro?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  heading?: T;
  blurb?: T;
  email?: T;
  bookingUrl?: T;
  footerTagline?: T;
  newsletter?:
    | T
    | {
        enabled?: T;
        blurb?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  background?: T;
  text?: T;
  mutedText?: T;
  surface?: T;
  border?: T;
  brandColor?: T;
  signalColor?: T;
  radius?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity_select".
 */
export interface IdentitySelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  showLogo?: T;
  logoHeight?: T;
  favicon?: T;
  browserTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loading-screen_select".
 */
export interface LoadingScreenSelect<T extends boolean = true> {
  enabled?: T;
  frameDuration?: T;
  overlayColor?: T;
  overlayOpacity?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  terms?: T;
  privacy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}