/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    posts: Post;
    testimonials: Testimonial;
    media: Media;
    subscribers: Subscriber;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    contact: Contact;
    theme: Theme;
    identity: Identity;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    identity: IdentitySelect<false> | IdentitySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Each project is one row on the homepage. Drag to reorder — the order here is the order visitors see.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Auto-filled from the title if left blank.
   */
  slug?: string | null;
  /**
   * Who it was for.
   */
  client?: string | null;
  year?: number | null;
  /**
   * Short tags — e.g. Identity, Web Design, Art Direction. Two or three is plenty.
   */
  disciplines?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One sentence on what this project was. Shown on the homepage row — keep it short; the image does the talking.
   */
  summary: string;
  /**
   * The single decisive image for this project. Landscape works best.
   */
  cover: number | Media;
  /**
   * Optional longer case study, shown on the project page.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * More images from the project, stacked below the write-up. Leave empty to show just the cover. Two half-width images in a row sit side by side.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Optional. A short line under the image.
         */
        caption?: string | null;
        /**
         * Full images stand alone; two halves in a row share the width.
         */
        size?: ('full' | 'half') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show this project on the homepage.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image the way you would to someone who cannot see it. This is read aloud by screen readers and shown if the image fails to load.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Posts on the blog page. The Blog link only appears in the site header once at least one post is published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-filled from the title if left blank.
   */
  slug?: string | null;
  /**
   * Posts are ordered newest first by this date.
   */
  publishedAt: string;
  /**
   * Untick to keep a draft hidden from the site.
   */
  published?: boolean | null;
  /**
   * One or two sentences shown on the blog page under the title.
   */
  excerpt: string;
  /**
   * Optional. Shown on the blog page and at the top of the post.
   */
  cover?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Real words from real clients. If none are published, the homepage simply omits this section — it never shows an empty shell.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Keep it to what they actually said. Shorter quotes land harder.
   */
  quote: string;
  name: string;
  /**
   * e.g. Founder
   */
  role?: string | null;
  company?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Uncheck to hide without deleting.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who asked to hear about new work. Export or delete any time.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  year?: T;
  disciplines?:
    | T
    | {
        label?: T;
        id?: T;
      };
  summary?: T;
  cover?: T;
  body?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        size?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  published?: T;
  excerpt?: T;
  cover?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  company?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every word on the homepage lives here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * The first thing anyone reads. Short — it is set very large, and long copy will not sit well.
   */
  heroLine: string;
  /**
   * One or two sentences under the headline.
   */
  heroIntro: string;
  /**
   * Shows a small live dot and the label below.
   */
  available?: boolean | null;
  availabilityLabel?: string | null;
  /**
   * Optional. Sits to the right of the headline on wide screens, and below it on narrower ones.
   */
  heroImage?: (number | null) | Media;
  /**
   * How much of the hero’s width the photo takes up, on wide screens.
   */
  heroImageSize?: number | null;
  workHeading: string;
  /**
   * Optional. Leave blank to let the work start immediately.
   */
  workIntro?: string | null;
  approachHeading: string;
  approachBody: string;
  /**
   * The things that make you easy to work with. Three is the sweet spot.
   */
  approachPoints?:
    | {
        title: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  blogHeading: string;
  /**
   * Optional. A line under the heading on the blog page.
   */
  blogIntro?: string | null;
  metaDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The one obvious next step, and the softer fallback for people not ready yet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  heading: string;
  blurb?: string | null;
  /**
   * The primary call to action.
   */
  email: string;
  /**
   * Optional scheduling link (Cal.com, Calendly). Shown next to the email.
   */
  bookingUrl?: string | null;
  newsletter?: {
    enabled?: boolean | null;
    blurb?: string | null;
  };
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Every colour on the site. Use each swatch to open a colour wheel, or type a hex code. The contrast panel below the neutrals updates live so you can see whether text stays readable. Toggle Live Preview (top right) to watch the homepage recolour as you edit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * The page background.
   */
  background: string;
  /**
   * Headings and body copy. Must read clearly on the background.
   */
  text: string;
  /**
   * Secondary text — captions, metadata, supporting lines.
   */
  mutedText: string;
  /**
   * Tinted panels: the approach band and image frames. Usually a hair off the background.
   */
  surface: string;
  /**
   * Hairlines and dividers.
   */
  border: string;
  /**
   * Buttons, links, emphasis, and the whole contact section. Text on it stays readable automatically — pick any colour.
   */
  brandColor: string;
  /**
   * The single bright note — the “available for work” dot. Used only as a small mark, so it can be as vivid as you like.
   */
  signalColor: string;
  /**
   * Applies to buttons, inputs and image corners.
   */
  radius: 'sharp' | 'soft' | 'round';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The site’s name and logo, the browser tab’s icon and title, and how each is used.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity".
 */
export interface Identity {
  id: number;
  /**
   * Shown in the header when no logo is uploaded (or it’s turned off below), and in the footer.
   */
  siteName: string;
  /**
   * Optional. A wide logo with a transparent background works best — SVG or PNG.
   */
  logo?: (number | null) | Media;
  /**
   * Show the logo in the header instead of the site name.
   */
  showLogo?: boolean | null;
  /**
   * How tall the logo renders in the header, in pixels.
   */
  logoHeight?: number | null;
  /**
   * Shown in the browser tab and bookmarks. Square and simple reads best — most browsers render it very small.
   */
  favicon?: (number | null) | Media;
  /**
   * The browser tab’s title, and the page title search engines see. Short reads best — under ~60 characters.
   */
  browserTitle: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroLine?: T;
  heroIntro?: T;
  available?: T;
  availabilityLabel?: T;
  heroImage?: T;
  heroImageSize?: T;
  workHeading?: T;
  workIntro?: T;
  approachHeading?: T;
  approachBody?: T;
  approachPoints?:
    | T
    | {
        title?: T;
        detail?: T;
        id?: T;
      };
  blogHeading?: T;
  blogIntro?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  heading?: T;
  blurb?: T;
  email?: T;
  bookingUrl?: T;
  newsletter?:
    | T
    | {
        enabled?: T;
        blurb?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  background?: T;
  text?: T;
  mutedText?: T;
  surface?: T;
  border?: T;
  brandColor?: T;
  signalColor?: T;
  radius?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity_select".
 */
export interface IdentitySelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  showLogo?: T;
  logoHeight?: T;
  favicon?: T;
  browserTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}